config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :items do
    resources :auctions, only: %i[new create]
  end
  resources :item_types
  resources :franchises
  resources :auctions , except: %i[create] do
    resources :bids, except: %i[show delete]
  end
  resources :bids, only: %i[delete]
  devise_for :users
  resources :users do
    post 'users/:id', to: 'users#topup'
  end
  root to: 'auctions#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_auction_list.html.erb
   <div>
    <div class="user-item-cards p-2" style="margin-top:2rem" data-paymentmodal-target="auctioncards">
    <% @auctions.each do |auction| %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">

        <% if auction.item.photo.attached? %>
      <%= cl_image_tag(auction.item.photo.key, class:'img-fluid', style:'height:300px;width:100%') %>
       <% else %>
        <%= image_tag 'https://source.unsplash.com/random/300×300', class:'img-fluid', style:'height:300px;width: 100% ;crop:fill' %>
      <% end %>
      <div class="category d-flex justify-content-center">
      <span><%= auction.item.franchise.name %></span>
        </div>
      <div class="title-product">
        <h3><%= auction.item.name %>
        <% if Time.now - Auction.where(item:auction.item)[0].end_time > 0 %>
          <span class="btn btn-danger" style="border-radius:15px;font-size:10px;color:white;">Ended</span>
        <% else %>
          <span class="btn btn-success" style="border-radius:15px;font-size:10px;color:white;">On-going</span>
        <% end %>
        </h3>
      </div>
      <div class="description-prod">

      <p class="timer-end-time">Auction End Time: <%= auction.end_time %></p>

      </div>
      <div class="card-footer">
        <div class="wcf-left"><span class="price mx-4">Min Bid : <%= auction.minimum_bid %></span></div>
        <div class="wcf-right"><%= link_to 'Bid now', auction, class:"btn btn-dark btn-wow",style:"border-radius:10px;margin-top:-5px;" %></div>
      </div>

      </div>
    </div>
    <% end %>
  </div>

app/views/shared/_banner.html.erb
<%# <div class="banner"> %>

<%# navbar/banner start %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon banner d-flex flex-column align-items-start">
  <div class="container-fluid">
    <%# logo + navbar section start%>
    <%= link_to root_path , class: "navbar-brand" do %>
      <%= image_tag "kickauction_logo_clear.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link",style:"color:white;" %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.username, current_user ? user_path(current_user) : users_path, class: "nav-link",style:"color:white;" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcg4Y51XjQ-zSf87X4nUPTQzsF83eFdZswTg&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <div class="d-flex">
              <%= link_to "Login", new_user_session_path, class: "nav-link",style:"color:white;" %>
              <%= link_to "Sign up" , new_user_registration_path, class:'nav-link',style:"color:white;" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%# logo + navbar section end %>

  <%# banner content %>
  <div class="banner-content d-flex flex-column">
    <div class="banner-text" data-controller="typed-js">
      <h1>KickAuction</h1>
      <h2>Fight for what you need.</h2>
    </div>
      <%# setting up typed js text for animation %>
      <div id="typed-strings">
        <h2>You bid. You win.</h2>
        <h2>At an auction keep your mouth shut</h2>
      </div>
    <div class="typed-text-body">
      <span id="typed"></span>
    </div>
  </div>
      <%# end of typed js script %>

</div>

  <%# navbar section end %>

<%# </div> %>

app/views/shared/_creator_auction_list.html.erb
  <div>
    <div class="user-item-cards p-2" data-paymentmodal-target="auctioncards">
    <% @auctions.each do |auction| %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">
      <% if auction.item.photo.attached? %>
        <%= cl_image_tag(auction.item.photo.key, class:"img-fluid", style:"height:300px;width:100%")%>
      <% else %>
        <%= image_tag "https://source.unsplash.com/random/300×300", class:"img-fluid", style:"height:300px;width:100%"%>
      <% end %>
      <div class="category d-flex justify-content-center">
      <span><%= auction.item.franchise.name %></span>
        </div>
      <div class="title-product">
        <h3><%= auction.item.name %>
        <% if Time.now - Auction.where(item:auction.item)[0].end_time > 0 %>
          <span class="btn btn-danger" style="border-radius:15px;font-size:10px;color:white;">Ended</span>
        <% else %>
          <span class="btn btn-success" style="border-radius:15px;font-size:10px;color:white;">On-going</span>
        <% end %>
        </h3>
      </div>
      <div class="description-prod">
        <p>Auction end time:</p>
        <p><%=  auction.end_time %></p>
      </div>
      <div class="card-footer">
        <div class="wcf-left"><span class="price">Min Bid : <%= auction.minimum_bid %></span></div>
        <div class="wcf-right"><%= link_to 'View', auction, class:"btn btn-dark btn-wow",style:"border-radius:10px;margin-top:-5px;" %></div>
      </div>

      </div>
    </div>
    <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_item_auction_list.html.erb
      <div data-action="click->newauction#select">
      <% if @item.photo.attached? %>

        <%= cl_image_tag(@item.photo.key, class:"img-fluid", style:"height:300px;width:100%")%>
      <% else %>
        <%= image_tag "https://source.unsplash.com/random/300×300", class:"img-fluid", style:"height:300px;width:100%"%>
      <% end %>

      <div class="category d-flex justify-content-center" >
        <span><%= @item.franchise.name %></span>
      </div>

      <div class="title-product">
        <h3><%= @item.name %>Myhi</h3>
      </div>

      <div class="description-prod">
        <p><%= @item.description %></p>
        <p><%=  @item.item_type.name %></p>
      </div>
      </div>

app/views/shared/_item_list.html.erb
  <div>
    <div class="user-item-cards p-2" data-paymentmodal-target="listcards">
    <% @items.each do |item| %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">

        <% if item.photo.attached? %>
            <%= cl_image_tag(item.photo.key, class:"img-fluid", style:"height:300px;width:100%")%>
        <% else %>
          <%= image_tag "https://source.unsplash.com/random/300×300", class:"img-fluid", style:"height:300px;width:100%"%>
        <% end %>

      <div class="category d-flex justify-content-center" >

        <span><%= item.franchise.name %></span>
      </div>

      <div class="title-product d">
        <h3><%= item.name %>
        <% if Auction.where(item:item).length.nonzero? %>
          <span class="btn btn-warning" style="border-radius:15px;font-size:10px;color:white;">Auctioned</span>
        <% end %>

        </h3>
      </div>

      <div class="description-prod">
        <p><%= item.description %></p>
        <p><%=  item.item_type.name %></p>
      </div>


          <div class="row">
            <div class="d-flex justify-content-around">

              <%= link_to "Create Auction", new_item_auction_path(item), class:"btn btn-dark btn-wow", style:  "border-radius:10px;font-size:12px" %>
              <%= link_to "Edit", edit_item_path(item), class:"btn btn-dark btn-wow", style:  "border-radius:10px;font-size:12px" %>
              <%= link_to "Delete", item_path(item), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-dark btn-wow", style:  "border-radius:10px;font-size:12px" %>
            </div>
          </div>
        </ul>
      </div>
    </div>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "kickauction_logo_clear.png" %>
    <% end %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.username , current_user ? user_path(current_user) : root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcg4Y51XjQ-zSf87X4nUPTQzsF83eFdZswTg&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <div class="d-flex">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              <%= link_to "Sign up" , new_user_registration_path, class:'nav-link' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_creation_form.html.erb
<div data-paymentmodal-target="newcreation">
  <%= simple_form_for(@item) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="col-xl-8 col-l-8 col-m-8  mx-auto">
      <div class="form-inputs">
        <%= f.input :name, label:"Name of item" %>
        <%= f.input :photo, as: :file %>
        <%= f.input :description, :input_html => { style:"height:150px" } %>
        <div class="d-flex justify-content-between flex-wrap">
          <%= f.association :franchise, :input_html => { style:"width:350px" } %>
          <%= f.association :item_type, :input_html => { style:"width:350px" } %>
        </div>
      </div>

    <div class="form-actions d-flex justify-content-center">
      <%= f.button :submit, class:"btn btn-warning user-button-large" %>
    </div>

  </div>
<% end %>

</div>

app/views/shared/_watchlist.html.erb
   <div>
    <div class="user-item-cards p-2" data-paymentmodal-target="watchlist">
    <% @bids.each do |bid| %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">

      <% if bid.auction.item.photo.attached? %>
        <%= cl_image_tag(bid.auction.item.photo.key, class:"img-fluid", style:"height:300px;width:100%")%>
      <% else %>
        <%= image_tag "https://source.unsplash.com/random/300×300", class:"img-fluid", style:"height:300px;width:100%"%>
      <% end %>

      <div class="category d-flex justify-content-center" >
        <span><%= bid.auction.item.franchise.name %></span>
      </div>

      <div class="title-product d">
        <h3><%= bid.auction.item.name %>
        <% if Time.now - Auction.where(item:bid.auction.item)[0].end_time > 0 %>
          <span class="btn btn-danger" style="border-radius:15px;font-size:10px;color:white;">Ended</span>
        <% else %>
          <span class="btn btn-success" style="border-radius:15px;font-size:10px;color:white;">On-going</span>
        <% end %>
        </h3>
      </div>

      <div class="description-prod">

        <p>End Time: <%= bid.auction.start_time %></p>
        <p>Minimum Bid: <%= bid.auction.minimum_bid %></p>
      </div>

                <div class="row">
            <div class="d-flex justify-content-around">
              <%= link_to "View", auction_path(bid.auction), class:"btn btn-dark btn-wow", style:  "border-radius:10px;font-size:12px" %>
            </div>
          </div>
      </div>
    </div>
    <% end %>
  </div>