config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :items do
    resources :auctions, only: %i[new create]
  end
  resources :item_types
  resources :franchises
  resources :auctions , except: %i[create] do
    resources :bids, except: %i[show delete]
  end
  resources :bids, only: %i[delete]
  devise_for :users
  resources :users do
    post 'users/:id', to: 'users#topup'
  end
  root to: 'auctions#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
  <div class="row">
    <div class="col-sm-3">
      <h3><%= link_to "Item list", items_path %></h3>
      <p></p>
    </div>
    <div class="col-sm-3">
      <h3><%= link_to "Auction", auctions_path  %></h3>
      <p></p>
    </div>
    <div class="col-sm-3">
      <h3><%= link_to "Reviews", reviews_path %></h3>
      <p></p>
    </div>
    <div class="col-sm-3">
      <h3><%= link_to "User Profile", users_path %></h3>
      <p></p>
    </div>
  </div>

<div class="d-flex justify-content-between">
  <p class="display-4 fs-2 text-white rounded bg-dark fst-italic"> Top up Credit
  <p class="display-4 fs-2 text-white rounded bg-dark fst-italic"> List your creation
  <p class="display-4 fs-2 text-white rounded bg-dark fst-italic"> Auction
  <p class="display-4 fs-2 text-white rounded bg-dark fst-italic"> Review
</div>


<div class="d-flex">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
   <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic"> Name of Auction </h1>
   </div>
  </div>
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark ms-2">
   <div class="col-md-6 px-0 d-grid gap-2">
    <%# <h1 class="display-4 fst-italic"> Name of Auction </h1> %>
    <div class="d-flex">
      <div>image</div>
      <div>
        <div>header</div>
        <div>rating</div>
      </div>
    </div>
    <div class="d-flex">
      <div>image</div>
      <div>
        <div>header</div>
        <div>rating</div>
      </div>
    </div>
    <div class="d-flex">
      <div>image</div>
      <div>
        <div>header</div>
        <div>rating</div>
      </div>
    </div>
   </div>
  </div>
</div>