config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :items do
    resources :auctions, only: %i[new create]
  end
  resources :item_types
  resources :franchises
  resources :auctions , except: %i[create] do
    resources :bids, except: %i[show delete]
  end
  resources :bids, only: %i[delete]
  devise_for :users
  resources :users do
    post 'users/:id', to: 'users#topup'
  end
  root to: 'auctions#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :franchise
  belongs_to :item_type
  belongs_to :creator, class_name: "User"
  belongs_to :owner, class_name: "User"
  has_one :review
  has_one_attached :photo
end

app/models/item_type.rb
class ItemType < ApplicationRecord
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @user = current_user
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @user = current_user
    @item = Item.new(item_params)
    @item.creator = current_user
    @item.owner = current_user

    # raise
    if @item.save
      redirect_to @user, notice: "Item was successfully updated."
    else
      render 'items/new'
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @user, notice: "Item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @user = current_user
    if Auction.where(item_id: @item).length.zero?
      @item.destroy
      respond_to do |format|
        format.html { redirect_to @user, warning: "Item was successfully destroyed." }
      end
    else
      redirect_to @user, notice: "Item on auction cannot be deleted."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :description, :franchise_id, :item_type_id, :photo)
    end
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, label:"Name of item" %>
      <%= f.input :photo, as: :file, class:"photo-preview" %>
      <%= f.input :description, :input_html => { style:"height:150px" } %>
      <div class="d-flex justify-content-between flex-wrap">
        <%= f.association :franchise, :input_html => { style:"width:350px" } %>
        <%= f.association :item_type, :input_html => { style:"width:350px" } %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-dark", style:"border-radius:10px; " %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', user_path(current_user), class:"btn btn-dark mt-2", style:"border-radius:10px; " %>

app/views/items/index.html.erb
<h1>Items</h1>

<div>
    <div class="user-item-cards p-2" data-paymentmodal-target="cards">
    <% @items.each do |item| %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">
        <% if item.photo.attached? %>
            <%= cl_image_tag(item.photo.key, class:'img-fluid', style:'height:300px;width:100%')%>
        <% else %>
          <%= image_tag 'https://source.unsplash.com/random/300×300', class:"img-fluid", style:'height:300px;width:100%'%>
        <% end %>

        <ul class="pl-0 pt-1" style="list-style-type:none;size">

          <li>Name: <%= item.name %></li>
          <li>Description: <%= item.description %></li>
          <li>Creator: <%= item.creator.username %></li>
          <li>Franchise: <%= item.franchise.name %></li>
          <%= link_to 'Show', item %>
        </ul>
      </div>
    </div>
    <% end %>
  </div>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<div class="pt-3 grid-container p-0">
  <div class="user-card">
    <h1>KickAuction</h1>
    <p>Welcome back <%= @user.username %>!</p>
  </div>

    <div class="user-balance mt-4 d-flex flex-row-reverse">
        <i class="fa-regular fa-wallet fa-2xl" style="margin-top:26px"></i>
        <h5 class="ml-3 p-3"> <%= @user.credit %></h5>
    </div>
</div>

<div class="d-flex justify-content-between">
  <%= link_to "List a creation", new_item_path, class:"btn btn-dark user-button-large" %>
  <%= link_to "Go to auctions", root_path, class:"btn btn-dark user-button-large" %>
  <%= link_to "Top up credit", root_path, class:"btn btn-dark user-button-large" %>
</div>


  <h1>List your creation</h1>

  <%= render 'shared/new_creation_form', item: @item %>

  <%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<div>
    <div class="user-item-cards p-2" data-paymentmodal-target="cards">
    <%= @item.name %>
    <div class="user-item-card-category p-2 bg-light">
      <div class="user-item-name mx-auto">
      <% if @item.photo.attached? %>
      <%= cl_image_tag @item.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
        <%= image_tag "https://source.unsplash.com/random/300×300", class:"img-fluid", style:"height:300px;width:400% crop: :fill"%>
      <ul class="pl-0 pt-1" style="list-style-type:none;size">
        <li>Description: <%= @item.description %></li>
        <li>Creator: <%=  @item.creator.username %></li>
        <li> Owner: <%= @item.owner.username %></li>
        <li> Franchise: <%= @item.franchise_id %></li>
        <li>Itemtype: <%= @item.item_type_id %></li>
      </ul>

<%= link_to 'Back', items_path %>